import {
  Rows3,
  CaseSensitive,
  ArrowDownUp,
  Search,
  GitCompareArrows,
  MoveHorizontal,
  ScanLine,
  Layers,
  ListOrdered,
  Link2,
  Hash,
  GitBranch,
  Network,
  Triangle,
  FolderTree,
  Waypoints,
  Route,
  ListTree,
  Shapes,
  Target,
  Grid3x3,
  GitFork,
  Binary,
  SquareStack,
  BarChart3,
  Table2,
  Sigma,
  Divide,
  type LucideIcon,
  Code2,
} from 'lucide-react';

export const iconMap: Record<string, LucideIcon> = {
  'rows-3': Rows3,
  'case-sensitive': CaseSensitive,
  'arrow-down-up': ArrowDownUp,
  search: Search,
  'git-compare-arrows': GitCompareArrows,
  'move-horizontal': MoveHorizontal,
  'scan-line': ScanLine,
  layers: Layers,
  'list-ordered': ListOrdered,
  'link-2': Link2,
  hash: Hash,
  'git-branch': GitBranch,
  network: Network,
  triangle: Triangle,
  'folder-tree': FolderTree,
  waypoints: Waypoints,
  route: Route,
  'list-tree': ListTree,
  shapes: Shapes,
  target: Target,
  'grid-3x3': Grid3x3,
  'git-fork': GitFork,
  binary: Binary,
  'square-stack': SquareStack,
  'bar-chart-3': BarChart3,
  'table-2': Table2,
  sigma: Sigma,
  divide: Divide,
};

export function getCategoryIcon(icon: string): LucideIcon {
  return iconMap[icon] ?? Code2;
}
